export const LOAD_DOGS_SUCCESS = "LOAD_DOGS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const SAVE_AS_FAVORITE = "SAVE_AS_FAVORITE";
export const REMOVE_AS_FAVORITE = "REMOVE_AS_FAVORITE";
